### PR TITLE
Refactor server + Add routes

### PR DESCRIPTION
**Pull request by xiej2520**
# Description

This PR modifies the peer node to consistently use the `FileInfo` and `FileInfoHash` datatypes throughout, closing https://github.com/sbu-416-24sp/orcanet-rust/issues/10.

It also refactors the server routes, splitting them up by team and provides the scaffolding (routes + return types) for the routes specified on the API sheet.

## Contributors

@xiej2520 was responsible for most of the `FileInfo`/`FileInfoHash`/`&Path` data type changes and server route refactoring and @reaovyd implemented a few Market features.

## Changes

* The README is updated to indicate how to set boot_nodes and public_address configuration options for the market, as well as a guide demoing the CLI interface.
* `market` has some commits pulled in which implement the Dialer and Listener handlers for the Kad network. It also has some changes to use the `FileInfoHash` types.

### FileInfo

* `peernode/src/peer-node/cli/mod.rs` has been modified to use the new `FileInfoHash` type and `&Path` consistently, as well as use the new file map in the store.
* `peernode/src/peer-node/consumer/encode.rs` has been updated to consistently use the `EncodedUser` type instead of `String` type encodings for Users.
* `peernode/src/peer-node/consumer/http.rs` now checks to see if a downloads folder exists and reports an error indicating the problem if it doesn't.
* `peernode/src/peer-node/consumer/mod.rs` has some slight changes with printing and calling `get_file_chunk` with the User type instead of the user encoding.
* `peernode/src/peer-node/peer/mod.rs` now correctly uses the `FileInfoHash` type and new API for `register_file` for both the local market and the (todo) kad market, correcting the previous PR.
* `peernode/src/peer-node/producer/http.rs` consistently uses the `FileInfoHash` type and has some slight printing changes.

### Server Routing

* `peernode/src/peer-node/routes/` this module has been refactored to contain all the routes for the HTTP server, split up by team. As of this PR, only some of the routes have been completely implemented, the rest are simply scaffholding to accept requests and return the correct data type. The main thing to review here is to verify that those compile. The routes that are implemented are:
  * `peernode/src/peer-node/routes/bubble_guppies/history.rs`
  * `peernode/src/peer-node/routes/bubble_guppies/jobs.rs`
  * `peernode/src/peer-node/routes/file_routes.rs`
  * `peernode/src/peer-node/routes/sea_pig/home.rs`
* `peernode/src/peer-node/server.rs` has been modified to accept the new routing

### FileInfo again

* `peernode/src/peer-node/store/mod.rs` now uses the new `FileInfo` types, as well as a single `HashMap<FileInfoHash, LocalFileInfo>` for all the files registered with the local producer, instead of the three HashMaps used before. It has also been modified to use `&Path` types wherever possible instead of `String`.
* `peernode/src/peer-node/transfer/files.rs` likewise implements the `FileInfo` and file map used by `store/mod.rs` above.
* `peernode/src/peer-node/transfer/jobs.rs` mostly has naming changes to match the new types.
* `proto/src/lib.rs` now returns `FileInfoHash` and provides some helper methods.

## Testing

The PR passes the Github Actions tests (https://github.com/daminals/orcanet-rust/actions/runs/8902734081).

It compiles and works with the peer node demo file transfer on my machine. The implemented HTTP server routes respond correctly.

### CODE REVIEW

**Comment by xiej2520** [comment]
@reaovyd @andrewctam @daminals this follows up from https://github.com/daminals/orcanet-rust/pull/27.

**Review by andrewctam — COMMENTED** [review]
Compiles on my machine and the routes can be called in postman. 
Routes are broken, but I believe these issues are fixed already in another branch.

**Review by andrewctam — APPROVED** [review]

**Review by reaovyd — APPROVED** [review]
LGTM (since this is stuff reviewed from other repo)

**Comment by daminals** [comment]
Why do we have different folders for each desktop team? Shouldn't the routes be organized by functionality rather than the requested team

**Comment by xiej2520** [comment]
Each team is responsible for a different page, so each module in each team is still responsible for different functionality. We could pull them all up a level and get rid of the team folders though.

**Comment by daminals** [comment]
> Each team is responsible for a different page, so each module in each team is still responsible for different functionality. We could pull them all up a level and get rid of the team folders though.

Ok, maybe this organization will help the desktop teams to debug the correct functionality for their purposes

**Review by devu1997 — APPROVED** [review]

**Pull request merged**
