### PR TITLE
Bootstrap New Orcanet-Rust Repo

### PR DESCRIPTION
**Pull request by daminals**
Utilizing the fetch and merge syntax of git ([https://stackoverflow.com/questions/1425892/how-do-you-merge-two-git-repositories](https://stackoverflow.com/questions/1425892/how-do-you-merge-two-git-repositories)), add both the peernode and market repositories so that we can work together and collaborate on future PRs

### CODE REVIEW

**Review by andrewctam — APPROVED** [review]

**Comment by daminals** [comment]
Fixes applied [so far]
- Docker configuration: Dylan
- GitHub Actions Workflows: Daniel
- Fetching from deprecated repos: Daniel
- Readme: Andrew/Gretta

Todos:
- Revive draft PRs from deprecated repos [does not need to be completed to merge this PR]

Testing status
- Was able to utilize the docker build to start both the market and the producer, and then retrieve both the large file (giraffe.mp4) and the small file (giraffe.jpg) with the consumer. The GitHub Actions workflows also successfully ran according to their specific targets (peernode vs market, calling reusable format workflow) This means that the repo is functional and ready to bootstrap.

Status: Ready to Merge

**Review by andrewctam — APPROVED** [review]
LGTM

**Review by reaovyd — APPROVED** [review]
LGTM, runs on my machine

**Review by ingrettable — APPROVED** [review]
Looks good to me! I was able to run this on my machine without docker :) 
I added a note to the read-me on how to run the program locally without docker.

**Comment by snitski** [comment]
LGTM

**Review by dyscott — APPROVED** [review]
LGTM, works on my machine locally or with Docker

**Review by Bexport — APPROVED** [review]
LGTM, ran with no problems on my end

**Review by snitski — APPROVED** [review]

**Pull request merged**
